### PR TITLE
Adding Contributing.md file

### LINKED ISSUE #13: Add CONTRIBUTING.md file
Add a `CONTRIBUTING.md` file in the root of the repository that contains this content:

```md
See the [Legesher contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)
```

Simple enough 👍 Please ask to be assigned to this issue so we don't have duplicates 😄

### PR DESCRIPTION
**Pull request by imgovind**
Fix #13

### CODE REVIEW

**Review by madiedgar — CHANGES_REQUESTED** [review]
Thank you so much @imgovind for heading this up! Could you actually just add the line from the issue and not the content found from the link? (this makes it easier to maintain if all the repositories are pointing to the same document 🙊) thank you!

**Comment by imgovind** [comment]
> Thank you so much @imgovind for heading this up! Could you actually just add the line from the issue and not the content found from the link? (this makes it easier to maintain if all the repositories are pointing to the same document 🙊) thank you!

I made the change as you requested. 😄

**Review by madiedgar — APPROVED** [review]
Amazing 👏  thank you!!

**Comment by madiedgar** [comment]
Congrats on merging your first pull request! 🎉🎉🎉 ❤️ **THANK YOU THANK YOU THANK YOU** ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R) only given to those who have chosen to give back.
We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by madiedgar** [comment]
@all-contributors please add @imgovind for doc

**Pull request merged**
